---
- hosts: windows
  tasks:

  - name: Install python on windows using the credentials
    win_package:
      path: \\DevOpsLab00\softwares\python-3.8.5.exe
      product_id: python8
      state: present
      user_name: domain\vmadmin1234
      user_password: 123456
      reboot_required: false