- name: install ssh
  hosts: 10.0.0.6

  tasks:

  - name: set the default shell to PowerShell
    win_regedit:
      path: HKLM:\SOFTWARE\OpenSSH
      name: DefaultShell
      data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      type: string
      state: present

  # Or revert the settings back to the default, cmd
  # - name: set the default shell to cmd
  #   win_regedit:
  #     path: HKLM:\SOFTWARE\OpenSSH
  #     name: DefaultShell
  #     state: absent