- name: Getting Started First Playbook
  hosts: all
  tasks:

  - name:  create local directory in ansible
    local_action:
      module: file
      path: /tmp/localdir
      state: directory        