---
- hosts: windows
  tasks:

  - name: Install python on windows using the credentials
    win_package:
      path: \\DevOpsLab00\softwares\python-3.8.5.exe
      product_id: python8
      state: present
      user_name: P2LP5CD64107QH\vmadmin
      user_password: Fiserv@123
      reboot_required: false