---

- name: Webserver configuration
  hosts: 10.0.0.23
  remote_user: vmadmin
  gather_facts: false
  become: true

  roles:
  - webserver
  
# - name: user managment
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: true

#   tasks:

#   - name: user managment
#     user: name={{user_name}} state=present

#   - name: install app
#     package: name=nano state=prsent
